application: mi-hai
version: 1
runtime: go
api_version: go1

handlers:

- url: /
  script: _go_app
- url: /root
  static_dir: root/static

- url: /hsl-ticket-price/
  static_files: hsl-ticket-price/index.html
  upload: hsl-ticket/price/index\.html
- url: /hsl-ticket-price
  static_dir: hsl-ticket-price
